// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using MT.Infra.Data.AppData;

#nullable disable

namespace MT.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250910183703_CreateTableServico")]
    partial class CreateTableServico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mototrack_backend_rest_dotnet.Models.ColaboradorEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_COLABORADOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("varchar2(9)")
                        .HasColumnName("MATRICULA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar2(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("MT_COLABORADORES");
                });

            modelBuilder.Entity("mototrack_backend_rest_dotnet.Models.MotoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_MOTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("NVARCHAR2(17)")
                        .HasColumnName("CHASSI");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("varchar2(11)")
                        .HasColumnName("MODELO");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("NVARCHAR2(7)")
                        .HasColumnName("PLACA");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar2(30)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.ToTable("MT_MOTOS");
                });

            modelBuilder.Entity("mototrack_backend_rest_dotnet.Models.ServicoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_SERVICO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ColaboradorId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_COLABORADOR");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar2(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<long>("MotoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_MOTO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar2(20)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("MotoId");

                    b.ToTable("MT_SERVICOS");
                });

            modelBuilder.Entity("mototrack_backend_rest_dotnet.Models.ServicoEntity", b =>
                {
                    b.HasOne("mototrack_backend_rest_dotnet.Models.ColaboradorEntity", "Colaborador")
                        .WithMany("Servicos")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mototrack_backend_rest_dotnet.Models.MotoEntity", "Moto")
                        .WithMany("Servicos")
                        .HasForeignKey("MotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Moto");
                });

            modelBuilder.Entity("mototrack_backend_rest_dotnet.Models.ColaboradorEntity", b =>
                {
                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("mototrack_backend_rest_dotnet.Models.MotoEntity", b =>
                {
                    b.Navigation("Servicos");
                });
#pragma warning restore 612, 618
        }
    }
}
